### ISSUE TITLE
Create UWP App for Split and GetFiles

### ISSUE THREAD

**Issue by awwshop** [awwshop/language#1]
https://github.com/awwshop/language/tree/master/docs/programming/docs/visual-basic

https://github.com/awwshop/language/blob/master/docs/programming/docs/visual-basic/docs/split.md

https://github.com/awwshop/language/blob/master/docs/programming/docs/visual-basic/docs/getfiles.md

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66279565-126e3a00-e867-11e9-8919-4c535ec168fa.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66279568-18fcb180-e867-11e9-84bf-7bf9a416df7f.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66288987-2b3f1580-e890-11e9-9531-c66216db0a90.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66289047-532e7900-e890-11e9-87ed-cd5db172c68f.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66289055-57f32d00-e890-11e9-8091-27b30eb706f4.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66339493-1eeea300-e8f8-11e9-9b56-fb154c470639.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66339740-9d4b4500-e8f8-11e9-84e9-0696dcd494cb.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66339826-c7046c00-e8f8-11e9-9896-d9c1425cf495.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66339890-eef3cf80-e8f8-11e9-80da-54d5076b03ef.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66339931-06cb5380-e8f9-11e9-8018-d76ace3d166a.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66339978-1ba7e700-e8f9-11e9-949e-8ad85219a74e.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66340771-c7056b80-e8fa-11e9-91f5-a6d6a91990a0.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66340996-354a2e00-e8fb-11e9-9757-15bf3f44e9ee.png)

**Comment by awwshop** [comment]
https://github.com/Microsoft/Xaml-Controls-Gallery/issues/80#issuecomment-502769732

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66341386-01bbd380-e8fc-11e9-8bed-b13b26b7bc0b.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66341417-14cea380-e8fc-11e9-95d8-eb2801655166.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66341435-20ba6580-e8fc-11e9-87f5-8424efbb8495.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66345162-4fd4d500-e904-11e9-8197-bbb6aaa8770c.png)

**Comment by awwshop** [comment]
This only seems to work from VS.

**Comment by awwshop** [comment]
https://developercommunity.visualstudio.com/content/problem/148375/uwp-executable-file-does-not-run.html

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66345989-0c7b6600-e906-11e9-83a2-56a1428864d6.png)

**Comment by awwshop** [comment]
https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/automate-launching-uwp-apps

**Comment by awwshop** [comment]
https://social.msdn.microsoft.com/Forums/en-US/1f3185a5-dc25-42af-80ea-477767d7411d/can-a-wpf-application-be-published-on-the-microsoft-store

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66350290-c925f500-e90f-11e9-8975-3c3b4c8de1e9.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66355968-1b6e1280-e91e-11e9-8d9a-15377ef4e2f9.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66356107-af3fde80-e91e-11e9-950c-ff6edef01b22.png)

`        ' https://docs.microsoft.com/uwp/api/windows.ui.popups.messagedialog
        ' https://docs.microsoft.com/uwp/api/windows.ui.popups.messagedialog.-ctor
        ' https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/buttons

`

**Comment by awwshop** [comment]
https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net

**Comment by awwshop** [comment]
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs

**Comment by awwshop** [comment]
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons

**Comment by awwshop** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.popups.popupmenu

**Comment by awwshop** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.popups.popupmenu.commands

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66436833-0a380b00-e9dd-11e9-8fa1-620bd9efbd6a.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66782836-7a3a0b80-ee8b-11e9-8627-f94d429fb7fd.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66782859-858d3700-ee8b-11e9-9d89-46409fc3a945.png)

**Comment by awwshop** [comment]
![image](https://user-images.githubusercontent.com/50279667/66782893-98077080-ee8b-11e9-808c-d3b7b59568eb.png)

**Comment by bjean54116** [comment]
I get this error message because I didn't set the appropriate  startup project and I lunch a run. I was running a UW on a device. Setting the start-up to Android fix that.

Before

![2019-10-18 (2)](https://user-images.githubusercontent.com/13802703/67107275-2173b700-f19a-11e9-9dbf-63c54b7d80b3.png)

After

![2019-10-18 (3)](https://user-images.githubusercontent.com/13802703/67107645-d8703280-f19a-11e9-80ae-0f251b7aa909.png)

**Comment by awwshop** [comment]
I've spent the last 20 years of my life learning Microsoft, I constantly get harassed when I talk about the technology in public. I'm no longer willing to lose everything for this, so UWP and X.F is something I am no longer willing to invest in. I'm sorry I misled everyone on UWP/X.F.
